name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ "**" ]
  workflow_call:

jobs:
  build-release-conan-2:
    name: Build Release (Conan 2)
    runs-on: ubuntu-latest

    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main
        with:
          version: 2.3.2

      - name: Fetch conan recipes
        uses: actions/checkout@v4

      - name: Install conan CI profile
        shell: bash
        run: |
          conan profile detect
          cp .github/workflows/ci_conan_profile "$(conan profile path default)"
          conan profile show

      - name: Build up-core-api conan package
        shell: bash
        run: |
          conan create --version 1.6.0-alpha2 up-core-api/release
          conan create --version 1.6.0-alpha3 up-core-api/release
          conan create --version 1.6.0-alpha4 up-core-api/release

      - name: Build up-cpp conan package
        shell: bash
        run: |
          conan create --version 1.0.0-rc0 --build=missing up-cpp/release
          conan create --version 1.0.0 --build=missing up-cpp/release
          conan create --version 1.0.1-rc1 --build=missing up-cpp/release
          conan create --version 1.0.1 --build=missing up-cpp/release

      - name: Build zenohc conan package
        shell: bash
        run: |
          conan create --version 0.11.0.3 zenohc-tmp/prebuilt
          conan create --version 0.11.0 zenohc-tmp/prebuilt
          conan create --version 1.0.0-rc4 zenohc-tmp/prebuilt
          conan create --version 1.0.0-rc5 zenohc-tmp/prebuilt
          conan create --version 1.0.0-rc6 zenohc-tmp/prebuilt

      - name: Build zenohcpp conan package
        shell: bash
        run: |
          conan create --version 0.11.0.3 zenohcpp-tmp/from-source
          conan create --version 0.11.0 zenohcpp-tmp/from-source
          conan create --version 1.0.0-rc4 zenohcpp-tmp/from-source
          conan create --version 1.0.0-rc5 zenohcpp-tmp/from-source
          conan create --version 1.0.0-rc6 zenohcpp-tmp/from-source

      - name: Build up-transport-zenoh-cpp conan package
        shell: bash
        run: |
          conan create --version 1.0.0-rc0 --build=missing up-transport-zenoh-cpp/release
          conan create --version 1.0.0-rc1 --build=missing up-transport-zenoh-cpp/release
          conan create --version 1.0.0-rc2 --build=missing up-transport-zenoh-cpp/release
          conan create --version 1.0.0-rc3 --build=missing up-transport-zenoh-cpp/release

      - name: List conan packages
        shell: bash
        run: |
          conan list '*'

  build-dev-conan-2:
    name: Build Developer (Conan 2)
    runs-on: ubuntu-latest

    steps:
      - name: Install Conan
        id: conan
        uses: turtlebrowser/get-conan@main

      - name: Fetch conan recipes
        uses: actions/checkout@v4

      - name: Install conan CI profile
        shell: bash
        run: |
          conan profile detect
          cp .github/workflows/ci_conan_profile "$(conan profile path default)"
          conan profile show

      - name: Build up-core-api conan package
        shell: bash
        run: |
          conan create --version 1.6.1-dev up-core-api/developer

      - name: Build up-cpp conan package
        shell: bash
        run: |
          conan create --version 1.0.1-dev --build=missing up-cpp/developer

      - name: Build zenohc conan package
        shell: bash
        run: |
          conan create --version 1.0.0-rc5 zenohc-tmp/prebuilt
          conan create --version 1.2.1 zenohc-tmp/prebuilt

      - name: Build zenohcpp conan package
        shell: bash
        run: |
          conan create --version 1.0.0-rc5 zenohcpp-tmp/from-source
          conan create --version 1.2.1 zenohcpp-tmp/from-source

      - name: Build up-transport-zenoh-cpp conan package
        shell: bash
        run: |
          conan create --version 1.0.0-dev --build=missing up-transport-zenoh-cpp/developer

      - name: Build up-transport-socket-cpp conan package
        shell: bash
        run: |
          conan create --version 1.0.0-dev --build=missing up-transport-socket-cpp/developer/

      - name: List conan packages
        shell: bash
        run: |
          conan list '*'

  # NOTE: In GitHub repository settings, the "Require status checks to pass
  # before merging" branch protection rule ensures that commits are only merged
  # from branches where specific status checks have passed. These checks are
  # specified manually as a list of workflow job names. Thus we use this extra
  # job to signal whether all CI checks have passed.
  ci:
    name: CI status checks
    runs-on: ubuntu-latest
    needs: [build-dev-conan-2, build-release-conan-2]
    if: always()
    steps:
      - name: Check whether all jobs pass
        run: echo '${{ toJson(needs) }}' | jq -e 'all(.result == "success")'
